### ISSUE TITLE
전문가 (HT) 번역 진행시, 업로드 한 참조 문서가 보이지 않음

### ISSUE THREAD

**Issue by srockstwo** [jnoh71/wisetranslate#4]
## Environment 
- IE 11, Windows 7
- 브라우저 관계 없음

## Repro Steps
1. 로그온
2. 신규로 전문가 번역(HT) 요청
3. 번역 지침과 참조 문서 업로드

## Problem
- 지침 코멘트는 요청 내역 란에서 확인되나, 참조 문서는 확인되지 않음
- 잘못된 참조문서를 삭제할 수 없음

## Screenshots
![default](https://user-images.githubusercontent.com/33149582/32158907-5f667ed6-bd8e-11e7-8abf-95e3697335e2.JPG)

**Comment by jnoh71** [comment]
By design.  Memsource에 업로드된 Reference 파일 목록을 가져올 수 없음.
