### ISSUE TITLE
[번역요청내역] 버튼명 불일치 

### ISSUE THREAD

**Issue by srockstwo** [jnoh71/wisetranslate#5]
## Environment 
- IE 11, Windows 7
- 브라우저 관계 없음

## Repro Steps
1. 로그온
2. 메인 화면에서 "번역요청내역" 버튼 클릭

## Problem
- 메인 화면 버튼명과 일치하지 않은 영문 버튼 명이 보임
![default](https://user-images.githubusercontent.com/33149582/32159975-1201f68e-bd93-11e7-9d08-552b080670ef.png)

**Comment by jnoh71** [comment]
Fixed in 2017-10-31
