### ISSUE TITLE
[프로파일] 버튼명 불일치

### ISSUE THREAD

**Issue by srockstwo** [jnoh71/wisetranslate#6]
## Environment 
- IE 11, Windows 7
- 브라우저 관계 없음

## Repro Steps
1. 로그온
2. 메인 화면에서 "번역요청내역" 버튼 클릭
3. 좌측  메뉴 열에서 "프로파일" 버튼 클릭

## Problem
- 메뉴 열 버튼 명과 일치하지 않은 영문 버튼명이 보임
![-1](https://user-images.githubusercontent.com/33149582/32160477-4c010936-bd95-11e7-80f9-71d30336abc8.png)

**Comment by jnoh71** [comment]
Fixed in 2017-10-31
