### ISSUE TITLE
마침표 처리 

### ISSUE THREAD

**Issue by srockstwo** [jnoh71/wisetranslate#7]
## Environment 
- IE 11, Windows 7
- 브라우저 관계 없음

## Repro Steps

1. 메인화면 "사용 방법" 섹션에 스크롤바 위치
2. [번역 주문 방법]란의 이미지 그림 클릭

## Problem

마침표가 없어야 하는 구문의 마침표가 표기되어 있음
![-2](https://user-images.githubusercontent.com/33149582/32161320-7857a9c4-bd98-11e7-9e8f-1ace008f51ed.png)

**Comment by jnoh71** [comment]
Fixed in 2017-10-31
