### ISSUE TITLE
[~과] Typo 

### ISSUE THREAD

**Issue by srockstwo** [jnoh71/wisetranslate#8]
## Environment 
- IE 11, Windows 7
- 브라우저 관계 없음

## Repro Steps

1. 메인화면 "사용 방법" 섹션에 스크롤바 위치
2. [사용 방법]  아래 위치한 다음 문장  
- 간편한 주문 절차**과** 신속한 번역

## Problem
![-3](https://user-images.githubusercontent.com/33149582/32213099-3386adc0-be5d-11e7-9317-6f737ae4ccf9.JPG)

**Comment by jnoh71** [comment]
Fixed 2017-10-31
