### ISSUE TITLE
확인되지 않은  [모든 언어 표시] 버튼 

### ISSUE THREAD

**Issue by srockstwo** [jnoh71/wisetranslate#9]
## Environment 
- IE 11, Windows 7
- 브라우저 관계 없음

## Repro Steps

1. 메인화면, 번역 요청 클릭
2. 휴먼 번역 선택
3. 언어 선택 과정에서 보여지는 참조 박스 내용 안에, 지원되지 않은 버튼 명이 있음
   
## Problem
보라색 박스 속 [**모든 언어 표시**] 버튼은 언어 선택 드롭 박스에서 확인되지 않음

![-4](https://user-images.githubusercontent.com/33149582/32216815-5b5f3fd6-be69-11e7-9361-c7e1fb83e35d.JPG)

**Comment by jnoh71** [comment]
Admin 계정으로 로긴할 때만 "모든 언어 표시" 보이는 것이었음.
Fixed 2017-10-31
